services:
  detailing-crm-signature-pad-pwa-develop:
    image: ${ENV_DETAILING_CRM_FRONTEND_SIGNATURE_PAD_PWA_IMAGE}
    container_name: ${SIGNATURE_PAD_PWA_CONTAINER_NAME}
    ports:
      - '${ENV_DETAILING_CRM_FRONTEND_SIGNATURE_PAD_PWA_EXTERNAL_PORT}:80'

    restart: always
    networks:
      - network

networks:
  network:
    name: ${ENV_NETWORK}
    external: true
